### ISSUE TITLE
Cannot have two children / side bar pieces of content? This will not pull up along with HUD piece

### ISSUE THREAD

**Issue by vbitzer** [GSA/centers-of-excellence#220]
sidebar-extra-content:
  - text: Working to improve customer experience and increase opportunities for America’s farmers and producers.
    img-class: farmloans
    button-link: /coe/farm-loans/index.html
    button-text: View the USDA Direct Farm Loans Journey

**Comment by cantsin** [comment]
I think the spaces for `children` were not formatted properly. Here's what I did for future reference:

```yaml
sidebar-extra-content:
  children:
    - text: Helping America’s seniors find access to affordable housing.
      img-class: affordhousing
      button-link: /coe/affordable-housing/index.html
      button-text: View the HUD Journey
    - text: Working to improve customer experience and increase opportunities for America’s farmers and producers.
      img-class: farmloans
      button-link: /coe/farm-loans/index.html
      button-text: View the USDA Direct Farm Loans Journey
```
