### ISSUE TITLE
Tagging by month; need anchor links for easier scrolling

### ISSUE THREAD

**Issue by vbitzer** [GSA/centers-of-excellence#227]
https://coe.gsa.gov/press/press.html

**Comment by cantsin** [comment]
I'm not sure what is meant by "tagging by month" but looking at this file, may I suggest reformatting to take advantage of Jekyll's capabilities? If we have a list of links, such as: 

```yaml
layout: default
title: Press
links:
  - month: November 2019
    children:
    - link: https://www.meritalk.com/articles/innovation-starts-with-accepting-failure-fed-leaders-say/
      text: Innovation Starts With Accepting Failure, Fed Leaders Say
      source: MeriTalk
    - link: https://www.federaltimes.com/opinions/2019/11/20/paving-the-way-for-government-to-improve-the-digital-customer-experience/
      text: Paving the Way for Government to Improve the Digital Customer Experience
      source: Federal Times
```

Then we can iterate over them:

```
    {% for entry in page.links %}
      <h2>{{entry.month}}</h2>
      <ul>
      {% for item in entry.children %}
        <li><a href="{{item.link}}">{{item.text}}</a> ({{item.source}})</li>
      {% endfor %}
      </ul>
    {% endfor %}
```

This ensures consistent formatting for all links, but another advantage of iterating over these links is that anchor links can more easily be added. Otherwise anchor links will have to be added manually, for each month/year, which seems fragile to me.
